version: '3.8'

services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: local-open-webui
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - RAG_EMBEDDING_ENGINE=openai
      - AUDIO_STT_ENGINE=openai
      - USE_OLLAMA=FAlse
    volumes:
      - open-webui:/app/backend/data
      - ./backend:/app/backend  # Mount your local backend directory
      - ./build:/app/build  # Mount your local build directory
    restart: always

volumes:
  open-webui:
    external: true